services:
  mariadb:
    container_name: mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOT_PASSWORD: $(DB_ROOT_PASSWORD)
    env_file:
      -.env
    volumes:
      -mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: